# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # Dongleless mode (right half as central)
  - board: cornix_left
    shield: cornix_indicator
    artifact-name: cornix_left

  - board: cornix_right
    shield: cornix_indicator
    artifact-name: cornix_right

  # Dongle mode (XIAO nRF52840 as central, both halves as peripherals)
  - board: seeeduino_xiao_ble
    shield: cornix_dongle_adapter cornix_dongle_eyelash
    snippet: zmk-usb-logging
    artifact-name: cornix_dongle_debug

  - board: cornix_ph_left
    shield: cornix_indicator
    snippet: zmk-usb-logging
    artifact-name: cornix_left_peripheral_debug

  - board: cornix_ph_right
    shield: cornix_indicator
    snippet: zmk-usb-logging
    artifact-name: cornix_right_peripheral_debug

  # Production dongle mode (without logging)
  - board: seeeduino_xiao_ble
    shield: cornix_dongle_adapter cornix_dongle_eyelash
    artifact-name: cornix_dongle

  - board: cornix_ph_left
    shield: cornix_indicator
    artifact-name: cornix_left_peripheral

  - board: cornix_ph_right
    shield: cornix_indicator
    artifact-name: cornix_right_peripheral

  # Settings reset
  - board: cornix_right
    shield: settings_reset
    artifact-name: reset
