name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "boards/**"
      - "config/**"
      - "build.yaml"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
